version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCOPE: "@welbex-test-blog/api"
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/01-init-schema.sql:/docker-entrypoint-initdb.d/01-init-schema.sql
      - ./db:/dump

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@me.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db:
  pgadmin_data:
