version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCOPE: "@alex-test-blog/api"
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./apps/api/.env
    # environment:
      # environment is taken from env_file
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@me.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db:
  pgadmin_data:
